### ISSUE TITLE
handleSubscription client code incorrectly handles subscription

### ISSUE THREAD

**Issue by bennypowers** [stripe-samples/creating-subscriptions#13]
The example code at https://github.com/stripe-samples/set-up-subscriptions/blob/e8b64c7f8ee6e49a12fedd1edca404329364466e/client/script.js#L90-L117 (and in the docs on the website) incorrectly types `subscription.latest_invoice` as being an object, and so on with it's children.

the correct code needs to look something like this pyramid of death:

```ts
async function confirmSubscriptionEffect(subscription: Stripe.Subscription): Promise<void> {
  if (subscription.status !== 'active') {
    if (!isString(subscription.latest_invoice)) {
      if (!isString(subscription.latest_invoice.payment_intent)) {
        const { status, client_secret: secret } = subscription.latest_invoice.payment_intent;
        if (status === 'requires_action' || status === 'requires_payment_method') {
          const { error, paymentIntent } = await stripe.confirmCardPayment(secret);
          if (error)
            // yadda yadda
          else 
            // badda bing
        }
      }
    }
  }
}
```

Since `latest_invoice` could very well be a string.

**Comment by jaunt** [comment]
In the server code it's being expanded, so would never be a string would it?

For example, from server.go, line 91.

**Comment by bennypowers** [comment]
So it is on https://github.com/stripe-samples/set-up-subscriptions/blob/9ae0b2cfda79fba4335d8ccef08955e39848c4f1/server/node/server.js#L43-L47

It might be worth making those defaults, or otherwise playing with the typings, as the average developer with a TypeScript-based IDE will encounter those null checks when doing the tutorial..

Thanks

**Comment by ctrudeau-stripe** [comment]
Hey @bennypowers thank you for the flag. And thank you @jaunt for adding the note about the expand parameter. We've recently updated the NodeSDK with types, I'll rewrite a server with all the typings to see what you are experiencing here. Thank you for the feedback.

**Comment by bennypowers** [comment]
@ctrudeau-stripe note that the typing anxiety is felt on the *client* specifically (since over there it's nullable)
