### ISSUE TITLE
golang webhook objecttype switch not right?

### ISSUE THREAD

**Issue by jaunt** [stripe-samples/creating-subscriptions#16]
objectType := event.Data.Object["object"].(string)
	Logger(INFO, "objectType %v", objectType)

	switch objectType {
	case "customer.subscription.created":
	case "customer.subscription.deleted":
	
My log shows object type as things like "subscription", or "setup_intent", but never the things being caught in the case statement.

**Comment by cjavilla-stripe** [comment]
good catch! Thanks for reporting
