### ISSUE TITLE
DotNet controller is missing a /subscription route

### ISSUE THREAD

**Issue by joefhall** [stripe-samples/creating-subscriptions#17]
The [client-side Javascript](https://github.com/stripe-samples/set-up-subscriptions/blob/master/client/script.js) calls a `/subscription` route:

```
function confirmSubscription(subscriptionId) {
  return fetch('/subscription', {
    method: 'post',
    headers: {
      'Content-type': 'application/json'
    },
    body: JSON.stringify({
      subscriptionId: subscriptionId
    })
  })
...
```

This is not handled in [the DotNet controller](https://github.com/stripe-samples/set-up-subscriptions/blob/master/server/dotnet/Controllers/SubscriptionsController.cs), although it is in at least the [PHP](https://github.com/stripe-samples/set-up-subscriptions/blob/3fee862c6caf7957f92fa540dfc3aec2b5869f44/server/php/index.php) and [Go](https://github.com/stripe-samples/set-up-subscriptions/blob/3fee862c6caf7957f92fa540dfc3aec2b5869f44/server/go/server.go) implementations.  I think this route should be handled in the DotNet controller too?  Otherwise the example doesn't work.  Thanks

**Comment by stefan-stripe** [comment]
Thanks for bringing this to my attention, I've added a fix! Let me know if you have any other concerns!

**Comment by joefhall** [comment]
Thanks very much @stefan-stripe and for the quick response! 👍
