### ISSUE TITLE
Does not work with declined cards

### ISSUE THREAD

**Issue by luisrunge** [stripe-samples/creating-subscriptions#22]
I thought it was my integration, but when testing the locally and on the demo link (https://lbq6y.sse.codesandbox.io/), this example does not work when the payment is not processed (insufficient_funds, lost_card, card_declined).

No message in the webpage, no webhook, no error

Using the following cards (https://stripe.com/docs/testing -> Testing for specific responses and errors)

4000000000000002
4000000000009995
4000000000009987
4000000000009979
4000000000000069
4000000000000127
4000000000000119

It seems that sending the data by POST to /create-customer something fails and returns error 500.

![stripe_error](https://user-images.githubusercontent.com/62224095/77837108-c684b980-7154-11ea-9ab6-a77e84f4637d.png)

So I have gone to the dashboard to see what information was in the webhook: Nothing, I did not see any attempt in Stripe CLI either.

There is no record of those actions in Stripe (I thought there would be something showing an error in the payment)

I only see a 402 error in the logs /v1/customers

![stripe_log](https://user-images.githubusercontent.com/62224095/77837111-c7b5e680-7154-11ea-9b3f-273f0ab29f93.png)

After many tests I understood that this example does not work with card_declines.

For all other cards, including 3D Secure cards that require authentication, this example works perfectly.

Thanks in advance for your support (And for the great work creating this example).

Best Regards

**Comment by ctrudeau-stripe** [comment]
Thanks for flagging. As per https://github.com/stripe-samples/set-up-subscriptions/issues/4 we will change this demo to support declined cards.

**Comment by luisrunge** [comment]
Hi @ctrudeau-stripe 
Just a quick question: If the issue still exist since November 2019 (according to #4  ), why the issue have been closed?
I think it should stay open until declined cards are actually included.

Is there any date estimate to have this fixed?
Thank you in advance for checking this topic and for your support.

Regards

**Comment by ctrudeau-stripe** [comment]
Hello @luisrunge, the demo is not meant to implement everything but show how to get started with subscriptions. If you'd like to learn more about declines you can read about them here: https://stripe.com/docs/declines.
