### ISSUE TITLE
Subscription tiered pricing

### ISSUE THREAD

**Issue by rudyhadoux** [stripe-samples/creating-subscriptions#24]
Hi,

Is it possible to find a subscription example with tiered pricing ?

**Comment by ctrudeau-stripe** [comment]
Hello @rudyhadoux, you can use this same sample. But set up your Stripe plans differently in the dashboard. 

Here is a doc on how to setup tiers: https://stripe.com/docs/billing/subscriptions/examples#volume-based-pricing

Once you setup tiers you can change this code: https://github.com/stripe-samples/set-up-subscriptions/blob/master/server/node/server.js#L43 to pass in quantity. 

`
const subscription = await stripe.subscriptions.create({
    customer: customer.id,
    items: [{ plan: process.env.SUBSCRIPTION_PLAN_ID, quantity: 5 }],
    expand: ['latest_invoice.payment_intent']
  });
`

Closing this, happy to help more here.

**Comment by rudyhadoux** [comment]
OK thanks.
This little example could be cool in Stripe API Reference => Create a Subscription.
