### ISSUE TITLE
Wrong Doc Api for subscription with 3D secure ?

### ISSUE THREAD

**Issue by fabrice-dresscodes** [stripe-samples/creating-subscriptions#25]
According to https://stripe.com/docs/billing/subscriptions/cards#create-subscription-code

You need to create subscription like this : 

`$subscription = \Stripe\Subscription::create([
  'customer' => $customer->id,
  'items' => [
    [
      'plan' => 'plan_FSDjyHWis0QVwl',
    ],
  ],
  'expand' => ['latest_invoice.payment_intent'],
]);`

But If you do so, with a 3D Secure authentification required, it will throw an exception and the $subscription object will be empty. So you can not do the next action....

I would sugger to change the code for : 

`$subscription = \Stripe\Subscription::create([
                'customer' => $customer->getStripeId(),
                'payment_behavior' => "allow_incomplete",
                'items' => [
                    [
                        'plan' => $product->getPlanStripeId(),
                    ],
                ],
                'expand' => ['latest_invoice.payment_intent'],
            ]);`

Using the parameter payment_behavior allow us to retrieve the subscription object, then use the payment intent to do the next action

On https://stripe.com/docs/api/subscriptions/create the doc already says :

> Use allow_incomplete to create subscriptions with status=incomplete if the first invoice cannot be paid. Creating subscriptions with this status allows you to manage scenarios where additional user actions are needed to pay a subscription’s invoice. For example, SCA regulation may require 3DS authentication to complete payment. See the SCA Migration Guide for Billing to learn more. This is the default behavior.

I think Billing Docs should have the same notice

**Comment by dmarczydlo** [comment]
do you have some update here? @fabrice-dresscodes

**Comment by ctrudeau-stripe** [comment]
Hello @fabrice-dresscodes, what API version are you on? The suggestion for the code in that doc and this sample is based on the most up to date API version.  With API version 2019-03-14 or newer it is defaulted to allow_incomplete. 

You can read about the change here: https://stripe.com/docs/billing/subscriptions/overview#incomplete-opt-in 

Hope that helps, in the future if you need immediate help with your integration feel free to join our IRC channel to get your questions answered ASAP. You can use https://webchat.freenode.net/ as a browser interface to join the channel, and the channel name is #stripe.

**Comment by adreyfus-stripe** [comment]
Hi everyone! There was a change in behavior that was pushed out on API version 2019-03-14 where we no longer fail creating the subscription if the payment fails to succeed. If you are on an older API version (which you can [check in the dashboard](https://dashboard.stripe.com/developers)) then you would see this automatic failing behavior. See https://stripe.com/docs/upgrades#2019-03-14 

Our samples are written assuming you're on a recent version of the API to demonstrate the most up to date behavior. Thank you for asking and sorry it took a while to respond!
