### ISSUE TITLE
Please expand samples to cover payment failure and requires_action (3DS) outcomes from Stripe docs

### ISSUE THREAD

**Issue by anuzis** [stripe-samples/creating-subscriptions#28]
Please expand these examples to cover the standard cases outlined in the "Implementing a subscription signup & payment flow" docs:
- https://github.com/stripe-samples/set-up-subscriptions/blob/master/server/python/server.py
- https://github.com/stripe-samples/set-up-subscriptions/blob/master/client/script.js

Specifically, at step 4: https://stripe.com/docs/billing/subscriptions/payment#signup-4
These samples don't show how to handle payment failure or customer action required outcomes:
- https://stripe.com/docs/billing/subscriptions/payment#handling-failure (outcome 3)
- https://stripe.com/docs/billing/subscriptions/payment#handling-action-required (outcome 4)

The code snippets in the documentation are semi-helpful, but there's ambiguity around exactly how it's recommended we handle this end-to-end. For example, if payment fails and we have an existing Subscription (status: incomplete) and Invoice (unpaid), should we send the unpaid invoice ID back to the client and have a distinct server endpoint for retrying payments where we POST the existing invoice ID along with the new payment method to resolve the existing invoice?  Is there a simpler / recommended way to do this with a single server endpoint?

First time working through a Stripe integration, I have 90%+ of everything working as expected (users can add/update payment methods via secure 3DS using SetupIntents, subscribe via new and existing payment methods without 3DS, remove payment methods, cancel & reactivate, etc.). The test card that always fails (4000000000009995) behaves correctly in local testing showing the card decline reason to the user with no subscription created or invoice to resolve. However, it's appears the payment failure at outcome 3 in the docs above occurs at a different stage of the payment flow, as does getting 3DS working for new subscriptions (Visa test card #: 4000002500003155).

The sample set-up-subscriptions code has no reference to outcomes 3&4 which seem important to cover before attempting to serve live customers with Stripe. There's likely near-zero customization required for my implementation compared to the standard way Stripe recommends handling outcomes 3 & 4 in the docs above. It'd be helpful to see these samples expanded covering these cases as well.

**Comment by AipackGit** [comment]
Yes. totally agree with @anuzis . 

I just realize this when i try to implement this code sample into my own application. There is no  proper handling when payment failed due to card errors. You can see in the demo app, when you use test card 4000000000009995 (insufficient_funds),  no feedback to user.

also would like to know the recommendation (sample code will be nice) of how to handle failed  3DS authentication  in context of resolving existing Subscription (status: incomplete) and Invoice (unpaid).

**Comment by anuzis** [comment]
Update: it appears these samples may already be sufficient. I inquired with Stripe developer support and they explained lines 97-98 do most of the heavy lifting for outcomes 3&4 above (ref: https://github.com/stripe-samples/set-up-subscriptions/blob/master/client/script.js#L97 ).

My Stripe integration is a combination of JS from multiple Stripe Elements examples, set-up-subscriptions examples, along with a few additional snippets from Stripe documentation, looks like I may have missed those two key lines when determining what needed to be brought together from different sources. Haven't 100% confirmed everything passes yet, but it's promising to see what looks like a solution here.

**Comment by ctrudeau-stripe** [comment]
Hello @anuzis and @AipackGit 👋 

You can check the example here: https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/client/script.js#L262-L404 for a better handling of these situations. 

Check the server folders for error handling there for payment attach as well: https://github.com/stripe-samples/subscription-use-cases/blob/master/fixed-price-subscriptions/server/node/server.js#L42-L69

These show handle all the outcomes on this doc https://stripe.com/docs/billing/subscriptions/payment

**Comment by cwfoo** [comment]
@ctrudeau-stripe Please update the broken links in your post. Thank you.

**Comment by ctrudeau-stripe** [comment]
Thank you, @cwfoo. I  updated the links above. We've moved to this repository now: https://github.com/stripe-samples/subscription-use-cases/ which has more use cases of business models.
