### ISSUE TITLE
Incorrect .env path in Go server

### ISSUE THREAD

**Issue by serboctor** [stripe-samples/creating-subscriptions#29]
The Go server is using `../../.env` as the .env path. According to your docs, the user should move the file to the chosen server directory. Accordingly the path should be `.env`. 
If a user follows the instructions and opens the page in the browser, they'll get 404.
The node server on the other hand correctly checks .env

**Comment by ctrudeau-stripe** [comment]
Thank you. Fixed with this: https://github.com/stripe-samples/set-up-subscriptions/commit/c160fa3f6c292a02f67d2f78ea7bbe123dd63010
