### ISSUE TITLE
Vanilla PHP rather than Slim?

### ISSUE THREAD

**Issue by Toryn02** [stripe-samples/creating-subscriptions#32]
Is it possible to get this code implemented in vanilla PHP rather than the Slim framework? Only a small percentage of PHP developers use Slim, and it would be great to see the official Stripe dev guidance on how to do this in vanilla PHP. Thanks very much!

**Comment by ctrudeau-stripe** [comment]
Hi there! We've actually been moving the PHP samples away from using Slim and adding a more traditional set up (e.g. https://github.com/stripe-samples/checkout-single-subscription/tree/master/client-and-server/server/php). 

We initially picked Slim so we could reuse the same client code across all the languages we support. There's only a couple of us working on these on the side so being able to reuse the client code keeps maintenance manageable. We've been slow at moving over all the samples to use this new structure, so apologies that you ran into one that hasn't been updated yet. 

Our docs at https://stripe.com/docs/billing have more generic PHP code snippets that might be easier to incorporate into your application in the meantime. Hope that helps!
