### ISSUE TITLE
Demo breaks with 4000008400001629

### ISSUE THREAD

**Issue by nimashariatian** [stripe-samples/creating-subscriptions#4]
FYI This demo breaks with card numbers such as `4000008400001629` .
Not sure if it is within the scope of this application but the logic does not handle things like card declined codes thrown with `Stripe::CardError`

**Comment by ctrudeau-stripe** [comment]
Thank you for flagging. I've added a ticket to support card_declines in this demo.

**Comment by nimashariatian** [comment]
great thanks @ctrudeau-stripe :) I would have also been satisfied with: "This is not within the scope of this project" lol

**Comment by ctrudeau-stripe** [comment]
It should be! :)
