### ISSUE TITLE
Client UI (CSS issues)

### ISSUE THREAD

**Issue by Brayan233** [stripe-samples/creating-subscriptions#5]
Hi, 
first,thanks for your amazing works.

I tried to use your "set-up-subscriptions sample" with PHP back-end.
But i have some css issue using your client UI ( see attachment)
![css_issue](https://user-images.githubusercontent.com/24452317/69162276-b137b880-0aec-11ea-8e4c-02712e94009d.PNG)

When i fill the card number input, he is merged with the expiration date input ..
And globally, the client UI doesn't looks like the one in your demo => https://lbq6y.sse.codesandbox.io/

Thx

**Comment by thorsten-stripe** [comment]
@Brayan233 thanks for flagging this! You should be able to fix on your end quickly by uncommenting https://github.com/stripe-samples/set-up-subscriptions/blob/master/client/css/global.css#L76

We will fix it here soon (cc @ctrudeau-stripe)

**Comment by Brayan233** [comment]
@thorsten-stripe fixed. thanks.
