### ISSUE TITLE
PHP Server example does not behave the same as Node example (no SCA handling)

### ISSUE THREAD

**Issue by mchlbowyer** [stripe-samples/creating-subscriptions#6]
Using the PHP server example code, it does not handle SCA or declines etc, it just throws an error for example:

```
Type: Stripe\Error\Card
Message: Payment for this subscription requires additional user action before it can be completed successfully. Please refer to the use of the `enable_incomplete_payments` parameter here: https://stripe.com/docs/billing/lifecycle#incomplete-opt-in
```

Can the PHP example be updated to function the same way as the Node example?

**Comment by mchlbowyer** [comment]
For anyone with the same issue, make sure your API version is set to the latest in the Stripe Dashboard

**Comment by adreyfus-stripe** [comment]
Thanks for troubleshooting and updating the ticket! We'll set the API version in the samples to make it clearer
