### ISSUE TITLE
Get 'authentication required' for THIS sample (not others)

### ISSUE THREAD

**Issue by philsmy** [stripe-samples/creating-subscriptions#7]
Using the CLI I cannot create this sample. Other samples do create.

I get 
```
$ stripe samples create set-up-subscription
> An error occurred.
authentication required
```

On macos 10.14 running homebrew.

**Comment by adreyfus-stripe** [comment]
@philsmy Thanks for reporting! We just pushed out a fix in the latest version of the CLI that should fix this. Can you try updating the CLI to v1.2.4 and running again: 

```
stripe samples create set-up-subscriptions
```
