### ISSUE TITLE
Python exceptions in Flask views aren't being returned as JSON

### ISSUE THREAD

**Issue by philgyford** [stripe-samples/creating-subscriptions#8]
In the Python example code, the [`create_customer()` view function](https://github.com/stripe-samples/set-up-subscriptions/blob/master/server/python/server.py#L38) ends with:

```python
    except Exception as e:
        return jsonify(e), 403
```

But if an error occurred I would end up with something like this in my Flask server log:

> TypeError: Object of type 'AuthenticationError' is not JSON serializable

I fixed this by changing the above lines to:

```python
    except Exception as e:
        return jsonify(error=str(e)), 403
```

Maybe there are better ways, but this works for me, and seems similar to [how the Flask docs suggest handling API errors](https://flask.palletsprojects.com/en/1.1.x/patterns/errorpages/#returning-api-errors-as-json).

I assume the other functions will be similar but I haven't got that far yet!

I'm using Flask 1.1.1 on Python 3.6.8.

**Comment by ctrudeau-stripe** [comment]
Thank you for the fix @philgyford. Adding it to the sample.
